// notifications.js - Apple-style Notification System

const DISMISSED_KEY = 'clarity_dismissed_notifications';

function getDismissedNotifs() {
    try {
        const data = localStorage.getItem(DISMISSED_KEY);
        return data ? JSON.parse(data) : [];
    } catch (e) {
        return [];
    }
}

function addDismissedNotif(text) {
    const arr = getDismissedNotifs();
    if (!arr.includes(text)) {
        arr.push(text);
        try {
            localStorage.setItem(DISMISSED_KEY, JSON.stringify(arr));
            if (window.syncToFirebase) window.syncToFirebase(DISMISSED_KEY, arr);
        } catch (e) { }
    }
}

function isDismissed(text) {
    const arr = getDismissedNotifs();
    const t1 = text.toLowerCase().trim();

    return arr.some(d => {
        const t2 = d.toLowerCase().trim();
        if (t1 === t2) return true;

        const words1 = new Set(t1.split(/\W+/).filter(w => w.length > 2));
        const words2 = new Set(t2.split(/\W+/).filter(w => w.length > 2));

        if (words1.size === 0 || words2.size === 0) {
            return t1.length > 5 && t2.length > 5 && (t1.includes(t2) || t2.includes(t1));
        }

        let intersection = 0;
        for (let w of words1) {
            if (words2.has(w)) intersection++;
        }

        const union = words1.size + words2.size - intersection;
        if (union === 0) return false;

        const similarity = intersection / union;
        return similarity >= 0.5; // Catch slight differences generated by AI
    });
}

function initNotificationContainer() {
    let container = document.getElementById('notification-container');
    if (!container) {
        container = document.createElement('div');
        container.id = 'notification-container';
        document.body.appendChild(container);
    }
    return container;
}

function showNotification(notificationData) {
    const notifText = notificationData.text;
    if (isDismissed(notifText)) return; // Skip if similar message was already dismissed

    const container = initNotificationContainer();

    const notif = document.createElement('div');
    notif.className = `apple-toast priority-${notificationData.priority || 'low'}`;

    let icon = '🔔';
    if (notificationData.type === 'urgent') icon = '⚠️';
    else if (notificationData.type === 'action') icon = '⚡';

    notif.innerHTML = `
        <div class="toast-icon">${icon}</div>
        <div class="toast-content">
            <span class="toast-text">${notificationData.text}</span>
        </div>
        <button class="toast-close">&times;</button>
    `;

    const closeBtn = notif.querySelector('.toast-close');
    closeBtn.addEventListener('click', () => {
        addDismissedNotif(notifText); // Remember that we closed it
        notif.classList.add('hide');
        setTimeout(() => {
            notif.remove();
        }, 300);
    });

    container.appendChild(notif);

    void notif.offsetWidth;
    notif.classList.add('show');
}

function processIntelligence(intelligence) {
    if (!intelligence) return;

    if (intelligence.notifications && intelligence.notifications.length > 0) {
        intelligence.notifications.forEach((notif, index) => {
            setTimeout(() => {
                showNotification(notif);
            }, index * 400);
        });
    }

    if (intelligence.today_focus) {
        setTimeout(() => {
            showNotification({
                type: 'info',
                text: `Focus: ${intelligence.today_focus}`,
                priority: 'high'
            });
        }, (intelligence.notifications ? intelligence.notifications.length : 0) * 400);
    }
}
